// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoRaEjyMpz0SSxZJQXXt1hJ-MAIJGFp4M',
    appId: '1:903225590492:web:49a01040fa551d28b56a19',
    messagingSenderId: '903225590492',
    projectId: 'medicare-unit',
    authDomain: 'medicare-unit.firebaseapp.com',
    storageBucket: 'medicare-unit.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYLXOjE7l_Lo73pjVUsjGjbn2PjuBmPrM',
    appId: '1:903225590492:android:89a9882f33b8fdcbb56a19',
    messagingSenderId: '903225590492',
    projectId: 'medicare-unit',
    storageBucket: 'medicare-unit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlL-wsmY4JKds9x01eRbMkeiZswbz5BtQ',
    appId: '1:903225590492:ios:d990eb93ac4ad03cb56a19',
    messagingSenderId: '903225590492',
    projectId: 'medicare-unit',
    storageBucket: 'medicare-unit.firebasestorage.app',
    iosClientId: '903225590492-urk937qtic8kf1bamugbhih333qp9fa2.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlL-wsmY4JKds9x01eRbMkeiZswbz5BtQ',
    appId: '1:903225590492:ios:d990eb93ac4ad03cb56a19',
    messagingSenderId: '903225590492',
    projectId: 'medicare-unit',
    storageBucket: 'medicare-unit.firebasestorage.app',
    iosClientId: '903225590492-urk937qtic8kf1bamugbhih333qp9fa2.apps.googleusercontent.com',
    iosBundleId: 'com.example.medicare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoRaEjyMpz0SSxZJQXXt1hJ-MAIJGFp4M',
    appId: '1:903225590492:web:c82e1221082e2617b56a19',
    messagingSenderId: '903225590492',
    projectId: 'medicare-unit',
    authDomain: 'medicare-unit.firebaseapp.com',
    storageBucket: 'medicare-unit.firebasestorage.app',
  );
}
